### ISSUE TITLE
Comma missing from line 59, leaking variable

### ISSUE THREAD

**Issue by gocom** [usablica/widearea#1]
From just looking at the code, there seems to be a missing comma/semi-colon. From the line:

```
wideAreaIcons    = document.createElement('div')
```

Which causes the fullscreenIcon variable to leak to global.

That said, if you haven't already, I would advice Linting/Hinting your code. There are some patterns you shouldn't do. Like all those defines inside loops.

**Comment by ehsandotnet** [comment]
It fixed.
