### ISSUE TITLE
Consider textarea margin to icon panel

### ISSUE THREAD

**Issue by afshinm** [usablica/widearea#12]

**Comment by sahat** [comment]
Here is a screenshot when you have a scrollbar in the text area region. Icon needs to be moved left a little.
![screenshot from 2013-05-27 17 21 07](https://f.cloud.github.com/assets/544954/569815/68214d1a-c713-11e2-92b4-4c4e6f68d9fb.png)

**Comment by heyvito** [comment]
This seems to be tricky. I'm going to code something to fix that asap.

Edit: Okay... Got a solution that works on Chrome 27(.0.1453.93) and Firefox 21.0, I'll wait until @afshinm merges my last pull request before creating a new one.

**Comment by afshinm** [comment]
@sahat Thanks for completing.
@victorgama Actually, yes.

**Comment by afshinm** [comment]
@victorgama I'll merge your last pull request today.

**Comment by heyvito** [comment]
Since #11 has been merged, tonight I'll be opening a PR to fix this.

**Comment by heyvito** [comment]
Already fixed?
