### ISSUE TITLE
Focus change on Tab

### ISSUE THREAD

**Issue by ryanguill** [usablica/widearea#2]
When expanded, TAB will change focus, but the expanded view means you can't tell what control does have focus.  Not sure the best answer, but I would say one of two options:

1). Hitting tab actually inserts a tab character (most likely what the user wanted in the first place), which would also work the same when the view is normal (not expanded).

2) Hitting TAB functions the same was as hitting ESC, if the view is expanded, it returns to normal.  Hitting TAB while not expanded continues to tab to the next element as usual.

**Comment by ehsandotnet** [comment]
It fixed before, Tab button works as \t
