### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by appkr** [usablica/widearea#28]
on line 144 of widearea.js 0.3.0

```
currentTextArea.className += (currentTextArea.className + " widearea").replace(/^\s+|\s+$/g, "");
```

This will produce:

```
<textarea class="form-controlform-control wideared"></textarea>
```

It should be written like this:

```
currentTextArea.className = (currentTextArea.className + " widearea").replace(/^\s+|\s+$/g, "");
```

**Comment by afshinm** [comment]
Thanks for report @appkr, could you please create a PR for this change?

**Comment by connyay** [comment]
Looks like this was already fixed... https://github.com/usablica/widearea/pull/22?
